### ISSUE TITLE
The plugin could use a better error detection

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#12]
When there is an error in SLS, (like jinja error) the status is still SUCCESS.

```
Response on state.sls deploy.states.rsync_static, "pillar={"pillar_entry_point": "deploy_server:project_configs:some-project:static", "project_name": "some-project"}" for roles:static_some-project:
[{
  "minion1": ["Rendering SLS 'base:deploy.states.rsync_static' failed: Jinja variable 'str object' has no attribute 'rsync_client_pwfile'"],
  "minion2": ["Rendering SLS 'base:deploy.states.rsync_static' failed: Jinja variable 'str object' has no attribute 'rsync_client_pwfile'"]
}]
Finished: SUCCESS
```

**Comment by mchugh19** [comment]
Right you are! Looks like the api doesn't return a fail value for that type of issue. I've worked up a quick test case and will get it fixed.

**Comment by zerthimon** [comment]
I'm having the same problem im my code that uses salt's python-api.
im my deploy script i'm running number of state.sls which returns a dict when there is no salt eror. If it returns a str or a list I just print it and rase an error, if its a dict, then I parse it (sorted by __run_num__ in every server) and report the errors for servers that have them.

I'm sure if that sequence would work well for functions other than state.sls though.

**Comment by mchugh19** [comment]
Alright, thanks for your patience. As you mentioned, it appears that the saltapi returns a jsonArray with error text for state failures. So here's a build that detects that case and marks it as a failure. I've tested it on all of our states, but that's not necessarily a complete test suite. If you could please test in your environment, and let me know if you see any situations where a successful call is marked as a failure? While not expected, it is always possible. 

https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.0-beta2

**Comment by zerthimon** [comment]
Here is an example of configuring a non-existing cmd.run command, which returns success:
```
SuccessConsole Output

Started by user zerthimon
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/test/workspace
Response on cmd.run moo for infra01:
[{"infra01": "/bin/sh: 1: moo: not found"}]
Finished: SUCCESS
```

The status for the bad SLS (array) works great though:
```
￼Console Output

Started by user zerthimon
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/test/workspace
ERROR occurred !
ERROR: One or more minion did not return code 0 for state.sls test_state for infra01:
[{"infra01": [
  "SLS test_state does not render to a dictionary",
  "Error when rendering state with contents: some crap"
]}]
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE
```

**Comment by zerthimon** [comment]
Response for pillar.get (with a wrong keyword):
Like in the previos example, str was returned for server.

[{"infra01": "ERROR executing 'pillar.get': The following keyword arguments are not valid: output=raw"}]

**Comment by zerthimon** [comment]
I'm having problem now with an sls with two steps which works without errors, but the build is failure.

**Comment by mchugh19** [comment]
Gah! Thanks for the quick feedback. The way the missing sls detection was coded up probably triggered on your removed, Pulled, and Already_Pulled keys. I'll work up a fix. 

As far as the other examples go, it looks like salt itself doesn't show them as errors. From the commandline the following are returned as successful and green:

# salt '*' cmd.run moo
minion2:
    /bin/sh: 1: moo: not found
minion1:
    /bin/sh: 1: moo: not found


# salt '*' pillar.get missingthing
minion2:
minion1:


So while not optimal, I don't think we should worry about those use cases.

**Comment by mchugh19** [comment]
@zerthimon could you please send me the entire json response from deploy.states.deploy_celery? You should be able to use the previously used curl commands in the shell script. 

In the output that you pasted, it looks like the return object may have started with  ```[{"celery01.mydomain.com": {``` 
but I would have expected it to be  
 ```[{"data":{"celery01.mydomain.com":{ ```

**Comment by zerthimon** [comment]
Here's JSON
```
{
  "info": [
    {
      "Function": "state.sls",
      "jid": "20160224195355807281",
      "Target": "celery01.mydomain.com",
      "Target-type": "glob",
      "User": "jenkins",
      "StartTime": "2016, Feb 24 19:53:55.807281",
      "Arguments": [
        "deploy.states.deploy_celery",
        {
          "pillar": {
            "app_tag": "84ff045f69b25c4143000aa744d771eed7373357",
            "app_name": "celery_task",
            "celery_instances": 1
          },
          "__kwarg__": true
        }
      ],
      "Minions": [
        "celery01.mydomain.com"
      ],
      "Result": {
        "celery01.mydomain.com": {
          "return": {
            "dockerng_|-celery-c-celery_task-1-container_|-c-celery_task-1_|-running": {
              "comment": "Container 'c-celery_task-1' is already configured as specified",
              "name": "c-celery_task-1",
              "start_time": "19:53:56.126125",
              "result": true,
              "duration": 7.122,
              "__run_num__": 1,
              "changes": {}
            },
            "dockerng_|-celery-celery_task-image_|-registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357_|-image_present": {
              "comment": "Image 'registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357' was pulled, but there were no changes",
              "name": "registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357",
              "start_time": "19:53:56.020751",
              "result": true,
              "duration": 105.165,
              "__run_num__": 0,
              "changes": {}
            }
          },
          "out": "highstate"
        }
      }
    }
  ],
  "return": [
    {
      "outputter": "highstate",
      "data": {
        "celery01.mydomain.com": {
          "dockerng_|-celery-c-celery_task-1-container_|-c-celery_task-1_|-running": {
            "comment": "Container 'c-celery_task-1' is already configured as specified",
            "name": "c-celery_task-1",
            "start_time": "19:53:56.126125",
            "result": true,
            "duration": "7.122 ms",
            "__run_num__": 1,
            "changes": {}
          },
          "dockerng_|-celery-celery_task-image_|-registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357_|-image_present": {
            "comment": "Image 'registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357' was pulled, but there were no changes",
            "name": "registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357",
            "start_time": "19:53:56.020751",
            "result": true,
            "duration": "105.165 ms",
            "__run_num__": 0,
            "changes": {}
          }
        }
      }
    }
  ]
}
```

**Comment by mchugh19** [comment]
Awesome, thanks!

This should probably detect the minion state failure without impacting other JSONArrays.
I've also removed the formatting when saving the json output to the environment variable. 

https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.0-beta4

**Comment by zerthimon** [comment]
Same job, NPE:
```
FailedConsole Output

Started by user zerthimon
[EnvInject] - Loading node environment variables.
[EnvInject] - Preparing an environment for the build.
[EnvInject] - Keeping Jenkins system variables.
[EnvInject] - Keeping Jenkins build variables.
[EnvInject] - Injecting as environment variables the properties content 
PROJECT=celery_task

[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting contributions.
Building in workspace /var/lib/jenkins/jobs/celery_task Deploy Celery (c-celery_task)/workspace
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
SALT_ROLE=c-celery_task
INSTANCES=1

[EnvInject] - Variables injected successfully.
Response on state.sls deploy.states.deploy_celery, "pillar={"app_name": "celery_task", "app_tag": "84ff045f69b25c4143000aa744d771eed7373357", "celery_instances": 1}" for roles:c-celery_task:
[{"celery01.mydomain.com": {
  "dockerng_|-celery-c-celery_task-1-container_|-c-celery_task-1_|-running":   {
    "comment": "Container 'c-celery_task-1' is already configured as specified",
    "name": "c-celery_task-1",
    "start_time": "13:51:32.050183",
    "result": true,
    "duration": 7.331,
    "__run_num__": 1,
    "changes": {}
  },
  "dockerng_|-celery-celery_task-image_|-registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357_|-image_present":   {
    "comment": "Image 'registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357' was pulled, but there were no changes",
    "name": "registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357",
    "start_time": "13:51:31.866638",
    "result": true,
    "duration": 183.33,
    "__run_num__": 0,
    "changes": {}
  }
}}]
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:396)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Send a message to Salt API' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by mchugh19** [comment]
Sorry about that. I forgot to set a default value for the newly added envvar checkbox. This should resolve that problem and will hopefully just work :)

https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.0-beta5

**Comment by zerthimon** [comment]
WOOT!
```
SuccessConsole Output

Started by user zerthimon
[EnvInject] - Loading node environment variables.
[EnvInject] - Preparing an environment for the build.
[EnvInject] - Keeping Jenkins system variables.
[EnvInject] - Keeping Jenkins build variables.
[EnvInject] - Injecting as environment variables the properties content 
PROJECT=celery_task

[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting contributions.
Building in workspace /var/lib/jenkins/jobs/celery_task Deploy Celery (c-celery_task)/workspace
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
SALT_ROLE=c-celery_task
INSTANCES=1

[EnvInject] - Variables injected successfully.
Response on state.sls deploy.states.deploy_celery, "pillar={"app_name": "celery_task", "app_tag": "84ff045f69b25c4143000aa744d771eed7373357", "celery_instances": 1}" for roles:c-celery_task:
[{"celery01.mydomain.com": {
  "dockerng_|-celery-c-celery_task-1-container_|-c-celery_task-1_|-running":   {
    "comment": "Container 'c-celery_task-1' is already configured as specified",
    "name": "c-celery_task-1",
    "start_time": "21:12:21.794084",
    "result": true,
    "duration": 7.406,
    "__run_num__": 1,
    "changes": {}
  },
  "dockerng_|-celery-celery_task-image_|-registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357_|-image_present":   {
    "comment": "Image 'registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357' was pulled, but there were no changes",
    "name": "registry.mydomain.com/celery_task:84ff045f69b25c4143000aa744d771eed7373357",
    "start_time": "21:12:21.683958",
    "result": true,
    "duration": 109.907,
    "__run_num__": 0,
    "changes": {}
  }
}}]
Notifying upstream projects of job completion
Finished: SUCCESS
```

Got an NPE with a missing pillar data:
```
[EnvInject] - Variables injected successfully.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at com.waytta.Utils.paramorize(Utils.java:125)
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:221)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Send a message to Salt API' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by zerthimon** [comment]
oops, the above NPE is because I specified an non-existing {{variable}} in the pillar parameter.

**Comment by zerthimon** [comment]
With the missing pillar data I get a jinja error that results in success, so this is still broken.
```
SuccessConsole Output

Started by user zerthimon
[EnvInject] - Loading node environment variables.
[EnvInject] - Preparing an environment for the build.
[EnvInject] - Keeping Jenkins system variables.
[EnvInject] - Keeping Jenkins build variables.
[EnvInject] - Injecting as environment variables the properties content 
PROJECT=celery_task

[EnvInject] - Variables injected successfully.
[EnvInject] - Injecting contributions.
Building in workspace /var/lib/jenkins/jobs/celery_task Deploy Celery (c-celery_task)/workspace
[EnvInject] - Executing scripts and injecting environment variables after the SCM step.
[EnvInject] - Injecting as environment variables the properties content 
SALT_ROLE=c-celery_task
INSTANCES=1

[EnvInject] - Variables injected successfully.
Response on state.sls deploy.states.deploy_celery for roles:c-celery_task:
[{"celery01.mydomain.com": ["Rendering SLS 'base:deploy.states.deploy_celery' failed: Jinja variable 'dict object' has no attribute 'app_name'"]}]
Notifying upstream projects of job completion
Finished: SUCCESS
```

**Comment by mchugh19** [comment]
Great. Things mostly work as I expect :)

That successful sls error is rather odd. Could you please capture the api's json response as you did above? 

Assuming that it returned as it did previously, jenkins **should** detect the failure. I've already added a test case of the following that is properly detected as a failure
```JSON
{"return": [
    {
      "outputter": "highstate",
      "data": {
        "celery01.mydomain.com": ["Rendering SLS XXX failed"]
      }
}]}
```

**Comment by mchugh19** [comment]
Running a state.sls on a nonexistant state name, seems to work as expected

```
Started by user anonymous
Building in workspace /home/xian/work/saltapi/work/jobs/fail state missing/workspace
Sending JSON: [{"client":"local","tgt":"*","expr_form":"glob","fun":"state.sls","arg":["failures.state"]}]
Running jid: 20160225134604225771
Waiting for 2 minions
2 minions are done
ERROR occurred !
ERROR: One or more minion did not return code 0 for state.sls failures.state for *:
[{
  "outputter": "highstate",
  "data": {"stratos.kix": ["No matching sls found for 'failures.state' in env 'base'"]}
}]
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE
```

**Comment by mchugh19** [comment]
Managed to duplicate. Try this out:
https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.0-beta6

**Comment by zerthimon** [comment]
Works great !!!

**Comment by mchugh19** [comment]
Changes released in 1.7.0
